apiVersion: v1
kind: Namespace
metadata:
  name: struts
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: struts-pvc
  namespace: struts
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: struts
  namespace: struts
  labels:
    app: struts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: struts
  template:
    metadata:
      labels:
        app: struts
    spec:
#      affinity:
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#          - labelSelector:
#              matchExpressions:
#              - key: app
#                operator: In
#                values:
#                - struts
#            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: struts
        image: reyl/struts:0.1
        ports:
        - containerPort: 8080
 #       resources:
 #         limits:
 #           cpu: 500m
 #         requests:
 #           cpu: 10m
        volumeMounts:
          - name: struts-pvc
            mountPath: "/data"
      volumes:
        - name: struts-pvc
          persistentVolumeClaim:
            claimName: struts-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: struts
  namespace: struts
spec:
  type: NodePort
  selector:
    app: struts
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: struts
#   namespace: struts
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: struts
#   minReplicas: 1
#   maxReplicas: 3
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 50
