apiVersion: v1
kind: Namespace
metadata:
  name: struts
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: struts-pv
spec:
  storageClassName: longhorn
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: struts-pv
  namespace: strutsc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: struts
  namespace: struts
  labels:
    app: struts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: struts
  template:
    metadata:
      labels:
        app: struts
    spec:
      containers:
        - name: struts
          image: reyl/struts:0.1
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: struts-pvc
              mountPath: "/data"
      volumes:
        - name: struts-pvc
          persistentVolumeClain:
            claimName: struts-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: struts
  namespace: struts
spec:
  type: NodePort
  selector:
    app: struts
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
