apiVersion: v1
kind: Namespace
metadata:
  name: struts
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: struts-pvc
  namespace: struts
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: struts
  namespace: struts
  labels:
    app: struts
spec:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - struts
      topologyKey: "kubernetes.io/hostname"
  replicas: 3
  selector:
    matchLabels:
      app: struts
  template:
    metadata:
      labels:
        app: struts
    spec:
      containers:
        - name: struts
          image: reyl/struts:0.1
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: struts-pvc
              mountPath: "/data"
      volumes:
        - name: struts-pvc
          persistentVolumeClaim:
            claimName: struts-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: struts
  namespace: struts
spec:
  type: NodePort
  selector:
    app: struts
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
